import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://researchtx-stage.tylerhost.net/CourtRecordsSearch/Home#!/home")
    page.get_by_role("link", name="Register", exact=True).click()
    page.get_by_role("textbox", name="First Name").fill("Test")
    page.get_by_role("textbox", name="First Name").press("Tab")
    page.get_by_role("textbox", name="Last Name").fill("Codegen")
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("codegen_publicuser@mailinator.com")
    page.get_by_role("textbox", name="Email").press("Tab")
    page.get_by_role("textbox", name="Password", exact=True).fill("Abcd1234")
    page.get_by_role("textbox", name="Password", exact=True).press("Tab")
    page.get_by_role("textbox", name="Confirm Password").fill("Abcd1234")
    page.get_by_role("button", name="Register").click()
    page.get_by_text("An account activation email").click()
    expect(page.get_by_role("alert")).to_contain_text("An account activation email has been sent to you. Click the link inside the email to activate your account.")
    expect(page.get_by_text("An account activation email")).to_be_visible()
    page1.goto("https://www.mailinator.com/")
    page1.get_by_role("textbox", name="Enter public inbox").click()
    page1.get_by_role("textbox", name="Enter public inbox").fill("codegen_publicuser")
    page1.get_by_role("button", name="GO").click()
    page1.get_by_role("cell", name="re:SearchTX - Activate Account").click()
    with page1.expect_popup() as page2_info:
        page1.locator("iframe[name=\"html_msg_body\"]").content_frame.get_by_role("link", name="Activate Account").click()
    page2 = page2_info.value
    page2.get_by_role("button", name="Sign in").click()
    page2.get_by_role("textbox", name="Email").click()
    page2.get_by_role("textbox", name="Email").fill("codegen_publicuser@mailinator.com")
    page2.get_by_role("textbox", name="Password").click()
    page2.get_by_role("textbox", name="Password").fill("Abcd1234")
    page2.get_by_role("button", name="Sign In").click()
    page2.goto("https://researchtx-stage.tylerhost.net/CourtRecordsSearch/account/#!/onboarding")
    with page2.expect_popup() as page3_info:
        page2.get_by_role("link", name="terms of use", exact=True).click()
    page3 = page3_info.value
    page3.get_by_text("Welcome to eFileTexas.gov,").click()
    expect(page3.get_by_text("Welcome to eFileTexas.gov,")).to_be_visible()
    page2.get_by_role("button", name="Continue").click()
    page2.get_by_role("textbox", name="Your Name or Your Firm /").fill("Tyler")
    page2.get_by_role("textbox", name="Your Name or Your Firm /").press("Tab")
    page2.get_by_role("textbox", name="Address Line 1 *").fill("Tyler")
    page2.get_by_role("textbox", name="Your Name or Your Firm /").click()
    page2.get_by_role("textbox", name="Your Name or Your Firm /").fill("Tyler test")
    page2.get_by_role("textbox", name="Address Line 2").click()
    page2.get_by_role("textbox", name="Address Line 2").fill("Tyler")
    page2.get_by_role("textbox", name="City *").click()
    page2.get_by_role("textbox", name="City *").fill("Tyler")
    page2.get_by_role("textbox", name="City *").press("Tab")
    page2.get_by_label("State *").select_option("number:17")
    page2.get_by_label("County *").select_option("number:331")
    page2.get_by_role("textbox", name="ZIP Code *").click()
    page2.get_by_role("textbox", name="ZIP Code *").fill("75070")
    page2.get_by_role("textbox", name="ZIP Code *").press("Tab")
    page2.get_by_role("textbox", name="Phone Number *").fill("1234567890")
    page2.get_by_role("button", name="Next").click()
    page2.get_by_text("General Public").click()
    page2.get_by_role("button", name="Continue").click()
    page2.get_by_role("button", name="Next").click()
    page2.get_by_role("button", name="Next").click()
    page2.get_by_role("button", name="Next").click()
    page2.get_by_role("button", name="Get Basic").click()
    page2.get_by_role("button", name="Maybe Later").click()
    expect(page2.get_by_role("textbox", name="Quick Search")).to_be_visible()
    page2.get_by_role("button", name="Profile Menu").click()
    page2.get_by_role("button", name="Sign out").click()
